name: CI

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Teine64.sln

      - name: Build (Release)
        run: dotnet build Teine64.sln -c Release --no-restore

      - name: Publish single-file win-x64
        run: dotnet publish src/Teine64/Teine64.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=false -o publish/win-x64

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: teine64-win-x64
          path: publish/win-x64/Teine64.exe

      - name: Create GitHub Release (tag push only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: publish/win-x64/Teine64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
